"""add_token_expires_at

Revision ID: 69d3aca0b7fb
Revises: 8d9cf785a4c2
Create Date: 2026-06-30 11:02:27.490125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d3aca0b7fb'
down_revision: Union[str, Sequence[str], None] = '8d9cf785a4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.Text(), nullable=True),
    sa.Column('compliance_matrix', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('proposal_draft', sa.Text(), nullable=True),
    sa.Column('final_checklist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_id'), 'tenders', ['id'], unique=False)
    op.create_index(op.f('ix_tenders_user_id'), 'tenders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_user_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
